const advancedBoothData = [
  {
    id: "a-1",
    name: "어서와, 반도체 회로제작은 처음이지?",
    img: "img/a/a-1.jpg",
    category: "첨단 제조 및 소재",
    subCategory: "차세대반도체",
    target: "초등 4학년 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~18:00",
    duration: 30,
    description:
      "반도체 회로 기초부터 실물 제작까지! 차세대반도체 혁신융합대학과 함께 직접 게임기 반도체 회로를 만들어보자!",
    details:
      "직접 게임기 회로를 제작하며, 반도체의 원리를 체험해보세요! 회로를 직접 만져보고 조립하면서 반도체가 실제로 어떻게 작동하는지 배울 수 있습니다. 제작 후 완성된 PCB게임기가 증정됩니다.",
    location: "차세대반도체 부스",
  },
  {
    id: "a-2",
    name: "3D펜으로 만드는 첨단소재 창의공작소",
    img: "img/a/a-2.jpg",
    category: "첨단 제조 및 소재",
    subCategory: "첨단소재나노융합",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 20,
    description:
      "3D 펜으로 이름표 키링, 책갈피 등 간단한 물체를 직접 제작하며 기초 3D 메이킹을 익히는 초간단 체험 프로그램",
    details:
      "3D펜을 사용하여 제공되는 도면과 제작 방법 안내 리플렛을 통해 제작",
    location: "첨단소재나노융합 부스",
  },
  {
    id: "a-3",
    name: "티프레임 스냅샷 : 테이크어샷 포토슛 팝팝팝!",
    img: "img/a/a-3.jpg",
    category: "첨단 제조 및 소재",
    subCategory: "차세대디스플레이",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description: "투명 OLED를 사용하여 원하는 이미지를 액자로 찰칵",
    details:
      "보이지만 비치지 않는, 미래의 빛을 찍다! 투명 OLED로 만나는 나만의 포토 액자! 빛과 화면이 하나 되는 차세대 디스플레이 기술, 투명 OLED를 직접 체험해보세요. 투명한 화면 위에 떠오른 다양한 이미지 중 마음에 드는 한 장을 선택하고, 그 이미지 뒤에서 사진을 촬영하면 — 마치 공중에 사진이 떠 있는 듯한 특별한 한 컷이 완성됩니다.",
    location: "차세대디스플레이 부스",
  },
  {
    id: "a-4",
    name: "차세대디스플레이 FAB : 디스플레이 공정속으로",
    img: "img/a/a-4.jpg",
    category: "첨단 제조 및 소재",
    subCategory: "차세대디스플레이",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description: "차세대디스플레이 FAB에서 실제 공정을 체험하는 프로그램",
    details:
      "빛이 화면이 되기까지 — 디스플레이의 모든 순간을 직접 보다! 디스플레이의 핵심 제조 기술인 6.5세대(6.5G) 공정 프로세스를 생생하게 재현한 현장에서 증착기 내부 구조부터 패널 형성 과정까지, 실제 크기와 설비를 기반으로 한 리얼한 제작 과정을 체험할 수 있습니다.",
    location: "차세대디스플레이 부스",
  },
  {
    id: "a-5",
    name: "키네틱LED Interactive",
    img: "img/a/a-5.jpg",
    category: "첨단 제조 및 소재",
    subCategory: "차세대디스플레이",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description: "실시간 동작 감지로 키네틱LED를 체험",
    details:
      "몸을 움직이면 LED가 반응한다! 움직임으로 즐기는 빛의 퍼즐, 키네틱LED 인터랙티브 게임! 실시간 동작 감지 기술을 기반으로 한 키네틱LED 체험존에서 당신의 몸짓이 그대로 게임 속 움직임이 됩니다. 테트리스, 같은그림찾기 등 직관적인 퍼즐형 미션을 몸을 움직여 직접 해결하세요.",
    location: "차세대디스플레이 부스",
  },
  {
    id: "a-6",
    name: "DIY 문자 코딩으로 만드는 나만의 장난감",
    img: "img/a/a-6.jpg",
    category: "첨단 제조 및 소재",
    subCategory: "차세대디스플레이",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description:
      "간단한 코딩과 조립으로 LED 장난감을 만들고, 완성품은 기념품으로 받아가세요!",
    details:
      "코딩으로 완성하는 나만의 LED 장난감! 간단한 전자 회로와 문자 코딩을 통해 빛과 메시지가 살아있는 DIY 키트를 직접 만들어보세요. 센서와 LED 모듈을 조립하고, 자신만의 문구나 패턴을 입력하면 나만의 맞춤형 스마트 오브제가 완성됩니다.",
    location: "차세대디스플레이 부스",
  },
  {
    id: "a-7",
    name: "손끝에서 펼쳐지는 스트레쳐블 첨단유연소재",
    img: "img/a/a-7.jpg",
    category: "첨단 제조 및 소재",
    subCategory: "첨단소재나노융합",
    target: "초등학생 이상",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 60,
    description:
      "손끝으로 만지고 느끼는 스트레쳐블 첨단유연소재, 고분자 네트워크의 신비로운 변화를 직접 체험해보세요!",
    details: "소재 개념 및 이론 설명 후 스트레쳐블 소재 체험 활동 진행",
    location: "첨단소재나노융합 부스",
  },
  {
    id: "a-8",
    name: "반도체를 분해해보자",
    img: "img/a/a-8.jpg",
    category: "첨단 제조 및 소재",
    subCategory: "반도체소부장",
    target: "모두",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~18:00",
    duration: 30,
    description: "반도체를 만드는 장비 내부를 보고, 뜯고, 조립해보는 VR 체험",
    details:
      "VR 체험을 통해 반도체를 만드는 장비 내부를 보고, 뜯고, 조립해보세요! 누구나 쉽게 VR 기기를 통해 참여할 수 있어요. 실제 현장과 같은 몰입감을 반도체소부장 컨소시엄에서 경험해보세요. VR 헤드셋을 쓰고, 손에 컨트롤러를 착용한 뒤 화면에 나타나는 지시에 따라 움직이면 금새 반도체 장비에 대해 이해할 수 있을 거에요!",
    location: "반도체소부장 부스",
  },
  {
    id: "a-9",
    name: "첨단소재 워터랩: 모링가의 비밀",
    img: "img/a/a-9.jpg",
    category: "첨단 제조 및 소재",
    subCategory: "첨단소재나노융합",
    target: "초등 고학년 이상",
    registration: "사전접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 40,
    description:
      "모링가 씨앗의 수질정화 실습을 통해 친환경 첨단소재의 개념을 체험",
    details:
      "1. 오염수를 제작한다. 2. 친환경 소재 모링가 추출액으로 오염수를 침전시킨다. 3. 정수된 물의 탁한 정도를 측정하여 비교한다.",
    location: "첨단소재나노융합 부스",
  },
];

export default advancedBoothData;
