const energyBoothData = [
  {
    id: "e-1",
    name: "내 손안의 작은 발전기",
    img: "img/e/e-1.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "중학생 이상",
    registration: "사전접수",
    date: "11.26.-11.28.",
    time: "15:00~17:00",
    duration: 40,
    description: "친환경에너지를 이해하고 내손으로 만들어보는 발전기",
    details: "친환경에너지를 이해하고 내손으로 만들어보는 발전기",
    location: "에너지신사업 부스",
  },
  {
    id: "e-2",
    name: "방탈출 프로그램 '교수님의 수상한 과제'",
    img: "img/e/e-2.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에코업",
    target: "모두",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~18:00",
    duration: 20,
    description:
      "미래 혁신 인재 필수 코스! '에코업 6대 과제' 속 환경 위기를 직접 해결하는 방탈출 프로그램",
    details:
      "방탈출을 통해 에코업 6대 과제를 흥미롭게 배우는 '교수님의 수상한 과제'. 15분간 진행되는 미션에 참여하여 에코업 6대 과제를 직접 해결하고 에코업 미래 혁신 인재가 되어보세요!",
    location: "에코업 부스",
  },
  {
    id: "e-3",
    name: "수소밸류체인 VR 체험",
    img: "img/e/e-3.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 20,
    description:
      "VR을 통해 수소 생산부터 활용까지 수소밸류체인의 전 과정을 생생하게 체험",
    details:
      "VR을 통해 수소 생산부터 활용까지 수소밸류체인의 전 과정을 생생하게 체험",
    location: "에너지신사업 부스",
  },
  {
    id: "e-4",
    name: "수소 스테이션",
    img: "img/e/e-4.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description:
      "수소전기차 등에 연료를 공급하기 위해 수소를 저장·충전하는 인프라 시설 체험",
    details:
      "수소전기차 등에 연료를 공급하기 위해 수소를 저장·충전하는 인프라 시설 체험",
    location: "에너지신사업 부스",
  },
  {
    id: "e-5",
    name: "수소연료전지자동차",
    img: "img/e/e-5.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "중학생 이상",
    registration: "사전접수",
    date: "11.27.-11.29.",
    time: "10:30~13:30",
    duration: 40,
    description:
      "수소연료전지의 원리를 이해하고, 친환경 자동차를 직접 만들어보는 체험형 교육 프로그램",
    details:
      "수소연료전지의 원리를 이해하고, 친환경 자동차를 직접 만들어보는 체험형 교육 프로그램",
    location: "에너지신사업 부스",
  },
  {
    id: "e-6",
    name: "수소자동차 롱룽",
    img: "img/e/e-6.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "중학생 이상",
    registration: "사전접수",
    date: "11.26.",
    time: "10:30~13:30",
    duration: 40,
    description: "수소자동차의 원리를 이해하고 직접 만들어보는 체험형 프로그램",
    details: "수소자동차의 원리를 이해하고 직접 만들어보는 체험형 프로그램",
    location: "에너지신사업 부스",
  },
  {
    id: "e-7",
    name: "압전에너지",
    img: "img/e/e-7.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 20,
    description:
      "발판 위를 누르면 전력이 생산되어 전력량을 보여주는 압전에너지 체험물",
    details:
      "발판 위를 누르면 전력이 생산되어 전력량을 보여주는 압전에너지 체험물",
    location: "에너지신사업 부스",
  },
  {
    id: "e-8",
    name: "업사이클링 카드지갑",
    img: "img/e/e-8.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "모두",
    registration: "사전접수",
    date: "11.26.-11.28.",
    time: "14:00~14:30",
    duration: 30,
    description: "친환경 소재로 만들어보는 나만의 카드지갑",
    details: "친환경 소재로 만들어보는 나만의 카드지갑",
    location: "에너지신사업 부스",
  },
  {
    id: "e-9",
    name: "우리집 알뜰에너지 연구소",
    img: "img/e/e-9.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에코업",
    target: "모두",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~18:00",
    duration: 10,
    description:
      "우리집 전기 도둑을 검거해보자! 가전제품 대기전력 측정 프로그램",
    details:
      "1단계: 가전제품 대기전력과 에너지소비효율등급 알아보기. 2단계: 가정에서 사용하는 가전제품(3종)에 대한 대기전력 직접 측정해보기. 3단계: 온라인(QR 접속) 만족도 조사 참여 후, 기념품(건전지 잔량 측정기) 받기",
    location: "에코업 부스",
  },
  {
    id: "e-10",
    name: "에코루프 키친스테이션",
    img: "img/e/e-10.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description:
      "식기세척기와 음식물처리기를 소형 히트펌프로 결합해 폐열을 활용함으로써 에너지 절감·편의성·친환경성을 동시에 구현한 미래형 주방 시스템 체험",
    details:
      "식기세척기와 음식물처리기를 소형 히트펌프로 결합해 폐열을 활용함으로써 에너지 절감·편의성·친환경성을 동시에 구현한 미래형 주방 시스템 체험. 삼성전자&고려대학교 미래 친환경 가전 아이디어 공모전 대상작",
    location: "에너지신사업 부스",
  },
  {
    id: "e-11",
    name: "이차전지 콘소시엄",
    img: "img/e/e-11.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "이차전지",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 15,
    description: "미래 에너지 중심, 이차전지를 '직접 보고, 느끼고, 체험하다!'",
    details:
      "VR과 실감형 콘텐츠로 누구나 쉽게 이해할 수 있는 체험존. 다면형 실감 콘텐츠 영상 체험, VR 전공정 투어모드, 이차전지 화재 대응 VR 등 다양한 체험 제공",
    location: "이차전지 부스",
  },
  {
    id: "e-12",
    name: "태양광 강아지 로봇",
    img: "img/e/e-12.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "중학생 이상",
    registration: "사전접수",
    date: "11.29.",
    time: "14:00~16:00",
    duration: 50,
    description:
      "태양광의 원리를 이해하고, 직접 전지판 실험 및 자동체 제작을 통해 친환경 에너지를 체험",
    details:
      "태양광의 원리를 이해하고, 직접 전지판 실험 및 자동체 제작을 통해 친환경 에너지를 체험",
    location: "에너지신사업 부스",
  },
  {
    id: "e-13",
    name: "태양전지 자동차경주",
    img: "img/e/e-13.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 20,
    description: "충전된 태양전지를 장착한 미니카를 이용한 트랙경주",
    details: "충전된 태양전지를 장착한 미니카를 이용한 트랙경주",
    location: "에너지신사업 부스",
  },
  {
    id: "e-14",
    name: "태양전지 패널",
    img: "img/e/e-14.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description:
      "태양광을 이용해 전력을 생산하며, 건물 외장재와 태양광 모듈을 일체화한 친환경 에너지 시스템에 사용되는 태양전지 패널 체험",
    details:
      "태양광을 이용해 전력을 생산하며, 건물 외장재와 태양광 모듈을 일체화한 친환경 에너지 시스템에 사용되는 태양전지 패널 체험. POSCO BIPV system 협찬",
    location: "에너지신사업 부스",
  },
  {
    id: "e-15",
    name: "플러스에너지빌딩",
    img: "img/e/e-15.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description:
      "건물 자체에서 소비하는 에너지보다 더 많은 에너지를 생산하여 순에너지 이익을 창출하는 차세대 친환경 건물을 직접 체험",
    details:
      "건물 자체에서 소비하는 에너지보다 더 많은 에너지를 생산하여 순에너지 이익을 창출하는 차세대 친환경 건물을 직접 체험",
    location: "에너지신사업 부스",
  },
  {
    id: "e-16",
    name: "LED로 그리는 탄소중립",
    img: "img/e/e-16.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에코업",
    target: "초등 고학년 이상",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~18:00",
    duration: 20,
    description: "탄소배출을 줄이는 나만의 LED 아크릴 조명을 만들어보자!",
    details:
      "1단계: 추억의 캡슐 뽑기! 탄소중립 생활에 대한 정보를 뽑기와 퀴즈로 알아보자. 2단계: LED 조명등 만들기. 3단계: 온라인(QR 접속)만족도 조사 참여 및 자리 정리",
    location: "에코업 부스",
  },
  {
    id: "e-17",
    name: "Space Green 우주 농부 인증 미션",
    img: "img/e/e-17.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "그린바이오",
    target: "초등학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 25,
    description:
      "애그테크(Ag-Tech)가 접목된 우주 수직농장부터 스마트 온실, 노지 수확까지 체험하고 우주 농부 인증을 받아보세요.",
    details:
      "2050년 우주 농부가 되기 위한 자격증을 획득하는 스토리형 체험관. 체험관1(수직농장): 수직농장 재배환경 체험. 체험관2(표본제작): 재배작물 표본을 제작해보고, 포토존에서 인증사진 촬영. 체험관3(스마트온실): 화성에 돔으로 만들어진 스마트온실에서 작물재배 환경 및 로봇재배 관람. 체험관4(스페이스 팜): 화성 노지에서 키우고 있는 GMO 식물 발견 및 수확 체험",
    location: "그린바이오 부스",
  },
  {
    id: "e-18",
    name: "보조배터리 제작 체험",
    img: "img/e/e-18.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "이차전지",
    target: "모두",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 60,
    description:
      "실제 제작 체험을 통해 배터리 제작 과정을 한눈에 알아볼 수 있습니다.",
    details:
      "보조배터리 조립 키트를 활용한 배터리 제작. 프로그램에 참여하시는 분들께는 귀여운 보조배터리를 드립니다.",
    location: "이차전지 부스",
  },
  {
    id: "e-19",
    name: "수력 풍력에너지 체험",
    img: "img/e/e-19.jpg",
    category: "에너지 및 환경 기술",
    subCategory: "에너지신사업",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description:
      "수력 및 풍력 에너지가 어떻게 생성되어 전기로 돌아오는지 과정을 알 수 있도록 설계된 체험물",
    details:
      "수력 및 풍력 에너지가 어떻게 생성되어 전기로 돌아오는지 과정을 알 수 있도록 설계된 체험물",
    location: "에너지신사업 부스",
  },
];
export default energyBoothData;
