const ictBoothData = [
  {
    id: "i-1",
    name: "기택이의 대모험",
    img: "img/i/i-1.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "빅데이터",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description: "오류 속에 숨은 진실, 기택이와 데이터 디버깅 체험",
    details:
      "데이터 오류를 시각화한 두 화면을 비교하여 '틀린 그림 찾기' 처럼 디버깅 체험 가능. COSS 빅데이터 경기과학기술대학교 서포터즈가 직접 개발한 교육용 게임",
    location: "빅데이터 부스",
  },
  {
    id: "i-2",
    name: "공감 조명: 오늘 너의 색은?",
    img: "img/i/i-2.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "사물인터넷",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description: "음성으로 기분을 말하면 전구 색상이 변하는 AI 체험",
    details:
      "오늘 당신의 기분은 어떤 색인가요? 말 한마디에 빛이 살아나는 특별한 체험! AI 음성 인식과 감정 분석 기술이 당신의 기분을 듣고, 전구의 색상과 밝기를 실시간으로 바꿔줍니다.",
    location: "사물인터넷 부스",
  },
  {
    id: "i-3",
    name: "꿈의 학교 속으로! 메타버스 캠퍼스 & 콘텐츠 여행",
    img: "img/i/i-3.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "실감미디어",
    target: "초등 고학년 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description: "꿈의 학교 속으로! 메타버스 캠퍼스 & 콘텐츠 여행",
    details:
      "현실의 한계를 넘어, 가상의 학교(건국대학교, 경희대학교, 계원예술대학교 등)에서 펼쳐지는 특별한 여정을 만나보세요! 실감미디어 기술로 구현된 메타버스 캠퍼스를 자유롭게 탐험하며, 미래형 교육 공간과 다양한 창의 콘텐츠를 직접 체험할 수 있습니다.",
    location: "실감미디어 부스",
  },
  {
    id: "i-4",
    name: "나는 누구일까?",
    img: "img/i/i-4.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "빅데이터",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description: "빅데이터가 랜덤키워드 5개를 줄게, 정답은 누가 맞출래?",
    details:
      "5개의 키워드를 랜덤으로 부여받아 공통적으로 연관된 단어 유추해 정답을 맞추는 게임. 제4기 COSS 빅데이터 경상국립대학교 서포터즈가 데이터사이언스 교육을 수료하여 만든 빅데이터 활용 게임",
    location: "빅데이터 부스",
  },
  {
    id: "i-5",
    name: "디지털 숲 명상 오디세이",
    img: "img/i/i-5.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "실감미디어",
    target: "초등 고학년 이상",
    registration: "사전접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 30,
    description:
      "가상현실로 구현된 숲 속 기상 변화 등을 배경으로 시각과 청각을 활용해 정신과 신체의 이완을 돕는 명상 프로그램 체험",
    details:
      "숲속의 휴식, 가상현실 명상 체험. 바쁜 일상 속에서 잠시 벗어나, 가상현실로 구현된 숲 속으로 들어가 보세요. 사계절의 숲 속 기상 변화와 어우러진 생생한 영상과 사운드가 눈과 귀를 감싸며, 정신과 신체의 긴장을 풀어주고 깊은 이완을 선사합니다.",
    location: "실감미디어 부스",
  },
  {
    id: "i-6",
    name: "AICOSS 메타버스 캠퍼스 체험",
    img: "img/i/i-6.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "인공지능",
    target: "중학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description: "AICOSS 메타버스캠퍼스 체험",
    details: "AICOSS 메타버스캠퍼스를 방문하여 각종 컨텐츠 탐구",
    location: "인공지능 부스",
  },
  {
    id: "i-7",
    name: "빅데이터 어워즈",
    img: "img/i/i-7.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "빅데이터",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description: "빅데이터 컨소시엄 학생들이 만든 우수 성과를 공유",
    details:
      "각종 경진대회와 빅데이터 혁신융합대학사업단이 제공하는 교과목의 우수 성과물 전시회. 서울시립대학교 2025 수도권 생활이동 데이터 해커톤 우수 성과물, 숙명여자대학교 학생들의 데이터 기반 프로젝트, 한동대학교 제5회 경상북도 공공데이터 활용 창업경진대회 우수 성과물",
    location: "빅데이터 부스",
  },
  {
    id: "i-8",
    name: "센서가 듣고, AI가 생각한다",
    img: "img/i/i-8.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "사물인터넷",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description:
      "센서가 내 목소리와 심장 소리를 읽고, AI가 판단하면 로봇이 곧바로 움직인다",
    details:
      "센서와 AI가 만드는 연결된 세상의 실험실. 음성 인식 마이크와 레이더(RADAR) 센서를 통해 체험자의 음성 명령과 심박 데이터를 수집하고, 수집된 데이터를 AI기술로 분석하여 로봇팔을 동작시킨다.",
    location: "사물인터넷 부스",
  },
  {
    id: "i-9",
    name: "스마트양식 디지털 트윈 체험: 모바일 로봇과 수질 센서를 활용한 자율 환경 관리",
    img: "img/i/i-9.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "사물인터넷",
    target: "중학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description: "모바일 로봇과 수질센서를 활용한 자율 환경 관리 체험",
    details:
      "제주도 특화 수질 데이터를 모사한 IoT 센서를 통해 환경정보를 수집 및 시각화, 디지털 트윈 기반 현장/원격 로봇 제어 체험",
    location: "사물인터넷 부스",
  },
  {
    id: "i-10",
    name: "스마트홈 캠 해킹, 누군가 지켜보고 있다",
    img: "img/i/i-10.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "데이터보안활용융합",
    target: "초등학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description: "스마트홈 해킹 시연을 통해 사생활 침해의 실체를 확인하세요",
    details:
      "집안을 지켜주는 편리한 홈캠, 하지만 누군가 해킹을 통해 당신의 일상을 훔쳐본다면? 정상적으로 작동하는 홈캠 화면 확인 → 공격자 PC를 통한 해킹 → 집안 곳곳의 모습과 저장 파일 탈취 시연 → 사생활 침해 위험성에 대한 인식 제고",
    location: "데이터보안활용융합 부스",
  },
  {
    id: "i-11",
    name: "톡톡 튀는 콘텐츠! 실감 팡팡 체험존",
    img: "img/i/i-11.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "실감미디어",
    target: "초등 고학년 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description: "실감미디어 학생들의 독창성 있는 우수 작품들을 직접 체험",
    details:
      "전국 대학생들이 함께한 창의적 성과를 한눈에 만날 수 있는 기회! 경진대회 최종 결선에 오른 학생들의 우수한 15개 작품을 직접 만나볼 수 있습니다. 관람객은 현실을 넘어선 몰입형 환경에서 창의적인 작품을 체험하고, 새로운 가능성을 탐색하는 특별한 경험을 하게 됩니다.",
    location: "실감미디어 부스",
  },
  {
    id: "i-12",
    name: "나의 왕자님, 공주님을 찾아라!",
    img: "img/i/i-12.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "빅데이터",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description: "이상형과 관련된 단어만 알려줘! 내가 이상형을 그려줄게!",
    details:
      "참가자들이 단어를 선택하면 자신이 좋아하는 이상형을 생성형 AI가 자동으로 그에 맞는 이상형을 그려줌. 제4기 COSS 빅데이터 전북대학교 서포터즈들의 작품. 체험 프로그램을 통해 찾은 나의 이상형을 포토카드에 담아 증정",
    location: "빅데이터 부스",
  },
  {
    id: "i-13",
    name: "인공위성 통신 체험관",
    img: "img/i/i-13.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "차세대통신",
    target: "초등학생 이상",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 15,
    description: "인공위성 발사부터 통신까지! 위성 통신 체험하기!",
    details:
      "메타버스로 구현된 인공위성 관제실에서 인공위성 발사부터 통신까지의 과정을 체험해보세요!",
    location: "차세대통신 부스",
  },
  {
    id: "i-14",
    name: "우리의 친절한 로봇의 반란",
    img: "img/i/i-14.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "데이터보안활용융합",
    target: "중학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 15,
    description:
      "해커의 손에 넘어가 멈추고 조작되는 순간, 로봇 해킹의 실체를 직접 체험하세요!",
    details:
      "언제나 친절하게 움직이던 로봇이 해킹 공격을 받는 순간, 친구에서 위협으로 변합니다. 서빙 로봇이 정상적으로 움직이는 과정 확인 → 해커의 공격으로 멈추거나 엉뚱하게 동작하는 모습 확인 → 로봇 해킹의 위험성과 다양한 산업으로 확산될 가능성 교육",
    location: "데이터보안활용융합 부스",
  },
  {
    id: "i-15",
    name: "탈출하라, 사이버 보안 위기 속 탈출기",
    img: "img/i/i-15.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "데이터보안활용융합",
    target: "중학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 30,
    description:
      "주변에 주어진 단서를 조합하여 사이버 위기 속 위험을 탈출하는 방탈출 게임!",
    details:
      "사이버 위기 상황을 배경으로 꾸며진 방 안에서, 참가자들은 제한된 시간 동안 흩어져 있는 단서들을 찾아내고 퍼즐을 풀어나가야 합니다. PC, 금고 등 실제 보안 위협을 상징하는 요소들이 배치된 공간 속에서 힌트를 해독해 나가며 최종 문을 열고 탈출해야만 미션이 완료됩니다.",
    location: "데이터보안활용융합 부스",
  },
  {
    id: "i-16",
    name: "Drone Under Attack: 하늘 위의 드론 위협",
    img: "img/i/i-16.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "데이터보안활용융합",
    target: "고등학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 15,
    description: "하늘 위에서 벌어지는 사이버 위협의 실체를 직접 체험해보세요!",
    details:
      "드론이 해커의 손에 넘어가는 순간을 직접 목격해보세요! 정상적으로 비행하는 드론이 갑작스러운 해킹 공격으로 오작동을 일으키며, 사이버 위협이 얼마나 실생활에 큰 영향을 미칠 수 있는지를 생생히 체험할 수 있습니다.",
    location: "데이터보안활용융합 부스",
  },
  {
    id: "i-17",
    name: "해킹이 부른 의료 사고",
    img: "img/i/i-17.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "데이터보안활용융합",
    target: "중학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description:
      "실제 의료기기 해킹 시연을 통해, 사이버 공격이 환자 생명에 미치는 치명적 위험을 직접 확인하세요!",
    details:
      "의료기기가 해커의 손에 넘어간다면, 환자의 생명은 어떻게 될까요? 인퓨전 펌프(의료기기)의 정상 작동 확인 → 해킹 공격으로 인한 이상 동작 시연 → 환자 안전에 미치는 위험성과 보안 필요성 교육",
    location: "데이터보안활용융합 부스",
  },
  {
    id: "i-18",
    name: "진짜처럼 짜릿! 손맛 체험존",
    img: "img/i/i-18.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "실감미디어",
    target: "초등 고학년 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description: "햅틱 디바이스(슈트와 장갑)를 착용한 후 복싱, 롤러코스터 체험",
    details:
      "진짜처럼 짜릿! 햅틱 손맛 체험존. 눈으로만 보는 VR을 넘어, 손끝으로 직접 느끼는 새로운 차원의 체험! VR 기반의 최첨단 햅틱 디바이스를 통해 가상의 물체를 잡고, 밀고, 당기며 현실 같은 촉감을 경험해 보세요.",
    location: "실감미디어 부스",
  },
  {
    id: "i-19",
    name: "AI가 만든 가짜를 잡아라",
    img: "img/i/i-19.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "데이터보안활용융합",
    target: "초등학생 이상",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 10,
    description:
      "숨은 단서를 찾아, AI가 만든 가짜와 사람의 진짜를 구분하는 재미를 느껴보세요!",
    details:
      "AI가 만든 결과물과 사람이 만든 결과물을 당신은 구분할 수 있을까요? 여러 카드에 적힌 결과물을 보고 AI 작품인지, 사람이 만든 것인지 추측 → AI가 만든 영상과 실제 영상을 비교하며 Fake의 위험성 확인 → 진짜와 가짜를 구분하는 눈을 기르는 보안 인식 교육",
    location: "데이터보안활용융합 부스",
  },
  {
    id: "i-20",
    name: "AI를 활용한 명화 속 몰입 체험",
    img: "img/i/i-20.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "인공지능",
    target: "중학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description: "AI를 활용한 명화속 몰입체험",
    details: "본인의 얼굴을 촬영하여 명화 작품속에 투영",
    location: "인공지능 부스",
  },
  {
    id: "i-21",
    name: "AI를 활용한 캐리커처 체험",
    img: "img/i/i-21.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "인공지능",
    target: "중학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description: "AI를 활용한 캐리커처 체험",
    details: "얼굴을 촬영하여 원하는 캐리커처(10종) 유형으로 체험",
    location: "인공지능 부스",
  },
  {
    id: "i-22",
    name: "Scent Memory",
    img: "img/i/i-22.jpg",
    category: "정보통신기술(ICT)",
    subCategory: "빅데이터",
    target: "모두",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:00",
    duration: 5,
    description: "나의 취향을 입력하면 데이터가 향수 레시피를 추천해준다구?!",
    details:
      "향료에 대한 빅데이터에 기반하여 개인 맞춤형 향수 레시피 지원 서비스. 서울대학교 빅데이터 혁신융합대학사업단 학생 커뮤니티 소속 팀이 직접 개발한 프로그램. 빅데이터가 추천해준 향수 레시피를 보고 실제 향수 샘플 만들기 체험 진행",
    location: "빅데이터 부스",
  },
  {
    id: "i-23",
    name: "AI 캐리커처",
    img: "img/i/i-23.jpg",

  },
  {
    id: "i-24",
    name: "AI 명화 속 몰입",
    img: "img/i/i-24.jpg",

  },
  {
    id: "i-25",
    name: "센서가 듣고 AI가 생각한다",
    img: "img/i/i-25.jpg",

  },
];

export default ictBoothData;
