const mobilityBoothData = [
  {
    id: "m-1",
    name: "드론 장애물 경주 체험",
    img: "img/m/m-1.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "항공드론",
    target: "초등 고학년 이상",
    registration: "현장접수",
    date: "11.28.-11.29.",
    time: "10:00~17:30",
    duration: 20,
    description:
      "드론 볼을 수동으로 조종하여 다양한 미션을 수행하는 체험 프로그램",
    details:
      "드론 볼을 직접 조종하며 미션을 수행하는 체험 프로그램. 장애물을 회피하며 조종 실력을 발휘. 긴장감과 재미, 드론 조종의 기본기를 한 번에",
    location: "항공드론 부스",
  },
  {
    id: "m-2",
    name: "블록코딩을 활용한 드론제어",
    img: "img/m/m-2.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "항공드론",
    target: "초등 고학년 이상",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:30",
    duration: 90,
    description: "블록코딩을 활용한 드론 실습 및 체험교육",
    details:
      "블록코딩을 통해 드론을 직접 제어해보는 체험 프로그램. 기본 드론 프로그래밍 교육부터 시뮬레이션, 실습까지 단계별 진행. 드론 제어 원리를 쉽고 재미있게 이해할 수 있는 기회 제공. 1. 기본 드론 프로그래밍 교육 2. 드론 프로그래밍 시뮬레이션 3. 기본 드론 프로그래밍 실습 4. 고급 드론 프로그래밍 실습",
    location: "항공드론 부스",
  },
  {
    id: "m-3",
    name: "일반인 로봇 교육프로그램 1 (경주로봇 만들기)",
    img: "img/m/m-3.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "지능형로봇",
    target: "초등학생 이상",
    registration: "사전접수",
    date: "11.26.-11.29.",
    time: "11:00~12:00",
    duration: 60,
    description: "일반인 로봇 교육 프로그램 1(경주로봇 만들기)",
    details:
      "로봇 키트를 활용한 로봇 교육 프로그램. 경주로봇을 만들어 트랙에서 다른 사람과 경기를 해본다.",
    location: "지능형로봇 부스",
  },
  {
    id: "m-4",
    name: "일반인 로봇 교육프로그램 2 (청소로봇 만들기)",
    img: "img/m/m-4.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "지능형로봇",
    target: "초등학생 이상",
    registration: "사전접수",
    date: "11.26.-11.29.",
    time: "12:00~13:00",
    duration: 60,
    description: "일반인 로봇 교육 프로그램 2 (청소로봇 만들기)",
    details:
      "로봇 키트를 활용한 로봇 교육 프로그램. 로봇청소기의 원리를 배울 수 있는 자율주행청소로봇 만들기!",
    location: "지능형로봇 부스",
  },
  {
    id: "m-5",
    name: "일반인 로봇 교육프로그램 3 (자이로 외발주행 로봇 만들기)",
    img: "img/m/m-5.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "지능형로봇",
    target: "초등학생 이상",
    registration: "사전접수",
    date: "11.26.-11.29.",
    time: "13:00~14:00",
    duration: 60,
    description: "일반인 교육 프로그램3(자이로 외발주행 로봇 만들기)",
    details:
      "로봇 키트를 활용한 로봇 교육 프로그램. 신기한 자이로 레일카의 원리에 빠져보아요",
    location: "지능형로봇 부스",
  },
  {
    id: "m-6",
    name: "일반인 로봇 교육프로그램 4 (유선 스파이더로봇 만들기)",
    img: "img/m/m-6.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "지능형로봇",
    target: "초등학생 이상",
    registration: "사전접수",
    date: "11.26.-11.29.",
    time: "14:00~15:00",
    duration: 60,
    description: "일반인 로봇 교육 프로그램4(유선 스파이더로봇 만들기)",
    details:
      "로봇 키트를 활용한 로봇 교육 프로그램. 유선으로 조종이 가능한 다족로봇을 만들어 보아요",
    location: "지능형로봇 부스",
  },
  {
    id: "m-7",
    name: "일반인 로봇 교육프로그램 5 (휴머노이드 이론교육 및 미션수행)",
    img: "img/m/m-7.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "지능형로봇",
    target: "중학생 이상",
    registration: "사전접수",
    date: "11.26.-11.29.",
    time: "15:00~16:30",
    duration: 90,
    description: "일반인 로봇 교육프로그램5(휴머노이드 이론교육 및 미션수행)",
    details:
      "고성능 소형 휴머노이드의 기본 원리 및 제어법을 교육하고 미션 경기를 직접 수행해 본다.",
    location: "지능형로봇 부스",
  },
  {
    id: "m-8",
    name: "AI 드로잉 로봇 및 오목 로봇 체험",
    img: "img/m/m-8.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "지능형로봇",
    target: "초등학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~18:00",
    duration: 20,
    description: "AI 드로잉 로봇 및 오목 로봇 체험",
    details: "AI 드로잉 로봇 및 오목 로봇을 직접 구동하여 원리를 체험",
    location: "지능형로봇 부스",
  },
  {
    id: "m-9",
    name: "AWS DeepRacer 자율주행 체험",
    img: "img/m/m-9.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "미래자동차",
    target: "키 100cm 이상",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:30",
    duration: 5,
    description: "미래자동차 자율주행 AI VS 인간, 운전 대결 승자는??!!",
    details: "사전신청하시고 예약하신 시간에 '미래자동차' 부스로 오시면 됩니다",
    location: "미래자동차 부스",
  },
  {
    id: "m-10",
    name: "ROBO SHOW (4족보행 로봇 및 테미)",
    img: "img/m/m-10.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "지능형로봇",
    target: "초등학생 이상",
    registration: "현장접수",
    date: "11.26.-11.29.",
    time: "10:00~18:00",
    duration: 30,
    description: "ROBO SHOW(4족보행 로봇 및 테미 체험)",
    details: "4족보행 로봇, 모바일 로봇 등을 활용한 로봇쇼",
    location: "지능형로봇 부스",
  },
  {
    id: "m-11",
    name: "UAM 조종 시뮬레이터 체험",
    img: "img/m/m-11.jpg",
    category: "미래 모빌리티 및 로봇",
    subCategory: "항공드론",
    target: "초등 고학년 이상",
    registration: "사전접수&현장접수",
    date: "11.26.-11.29.",
    time: "10:00~17:30",
    duration: 30,
    description: "UAM 조종법 교육 및 시뮬레이터 탑승 조종 체험",
    details:
      "UAM(도심항공교통) 조종법을 배우고 직접 체험할 수 있는 프로그램. 기본적인 조종 원리를 교육받은 후 시뮬레이터에 탑승하여 조종 진행. 실제 상황과 유사한 환경에서 조종 감각과 몰입도를 경험. UAM 조종 방법에 대해 기초 교육을 수행한 후 UAM 조종 시뮬레이터에 탑승하여 이륙, 천이, 선회 등의 기동을 수행하고 안전하게 착륙까지 완료",
    location: "항공드론 부스",
  },
];

export default mobilityBoothData;
